server:
  port: 8888
  servlet:
    context-path: /thymeleaf

spring:
  thymeleaf:
    # 配置视图路径前缀
    prefix: classpath:/templates/
    # 配置视图模板后缀
    suffix: .html
    mode: html
    # 关闭缓存
    cache: false