server:
  port: 8888
  servlet:
    context-path: /redis

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 10
        max-idle: 500
        min-idle: 0
    timeout: 10000